[build]
  command = "cp next.config.netlify.js next.config.js && npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Plugin do Next.js para Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"